### ISSUE TITLE
Can not compile on khadas vim3 kernel-5.18.0

### ISSUE THREAD

**Issue by jiratto** [numbqq/encoder_libs_aml#4]
/usr/bin/ld: /tmp/ccB4R6kJ.o: in function `do_cmd':
ge2d_feature_test.c:(.text+0x21f0): undefined reference to `aml_ge2d_attach_dma_fd'
/usr/bin/ld: ge2d_feature_test.c:(.text+0x2214): undefined reference to `aml_ge2d_attach_dma_fd'
/usr/bin/ld: ge2d_feature_test.c:(.text+0x2238): undefined reference to `aml_ge2d_attach_dma_fd'
/usr/bin/ld: ge2d_feature_test.c:(.text+0x2258): undefined reference to `aml_ge2d_config'
/usr/bin/ld: ge2d_feature_test.c:(.text+0x2288): undefined reference to `aml_ge2d_execute'
/usr/bin/ld: ge2d_feature_test.c:(.text+0x22e8): undefined reference to `aml_ge2d_detach_dma_fd'
/usr/bin/ld: ge2d_feature_test.c:(.text+0x22f4): undefined reference to `aml_ge2d_detach_dma_fd'
/usr/bin/ld: ge2d_feature_test.c:(.text+0x2300): undefined reference to `aml_ge2d_detach_dma_fd'
/usr/bin/ld: ge2d_feature_test.c:(.text+0x231c): undefined reference to `aml_ge2d_process'
/usr/bin/ld: /tmp/ccB4R6kJ.o: in function `do_blend':
ge2d_feature_test.c:(.text+0x291c): undefined reference to `aml_ge2d_process'
/usr/bin/ld: ge2d_feature_test.c:(.text+0x2b70): undefined reference to `aml_ge2d_process'
/usr/bin/ld: ge2d_feature_test.c:(.text+0x2d64): undefined reference to `aml_ge2d_process'
/usr/bin/ld: ge2d_feature_test.c:(.text+0x2fa8): undefined reference to `aml_ge2d_process'
/usr/bin/ld: /tmp/ccB4R6kJ.o:ge2d_feature_test.c:(.text+0x31f4): more undefined references to `aml_ge2d_process' follow
/usr/bin/ld: /tmp/ccB4R6kJ.o: in function `main_run':
ge2d_feature_test.c:(.text+0x4070): undefined reference to `aml_ge2d_init'
/usr/bin/ld: ge2d_feature_test.c:(.text+0x4090): undefined reference to `aml_ge2d_mem_alloc'
/usr/bin/ld: ge2d_feature_test.c:(.text+0x4148): undefined reference to `aml_ge2d_invalid_cache'
/usr/bin/ld: ge2d_feature_test.c:(.text+0x42e8): undefined reference to `aml_ge2d_mem_free'
/usr/bin/ld: ge2d_feature_test.c:(.text+0x42f0): undefined reference to `aml_ge2d_exit'
/usr/bin/ld: /tmp/ccB4R6kJ.o: in function `main':
ge2d_feature_test.c:(.text+0x4438): undefined reference to `pthread_create'
/usr/bin/ld: ge2d_feature_test.c:(.text+0x44a4): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make: *** [Makefile:16: all] Error 1
